# config.yaml
CONFIG_NAME: "localnet"

# Time parameters
SECONDS_PER_SLOT: 2
SECONDS_PER_ETH1_BLOCK: 2
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 16

# Fork epochs (todos en epoch 0 = activos desde el inicio)
GENESIS_FORK_VERSION: 0x00000000
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 18446744073709551615  # uint64 max → desactivado

# Terminal conditions (deben coincidir con Geth)
TERMINAL_TOTAL_DIFFICULTY: "0"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Deposit contract (puedes dejarlo, aunque no se use en localnet)
DEPOSIT_CHAIN_ID: 1337
DEPOSIT_NETWORK_ID: 1337
DEPOSIT_CONTRACT_ADDRESS: "0x0000000000000000000000000000000000000000"