CONFIG_NAME: localnet

# Parámetros base de red
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 8
MIN_GENESIS_TIME: 1730000000
GENESIS_DELAY: 5
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32
EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 8
MAX_VALIDATORS_PER_COMMITTEE: 2048

# Fork versions personalizadas (no colisionan con mainnet)
GENESIS_FORK_VERSION: 0xAABBCC01
ALTAIR_FORK_VERSION: 0xAABBCC02
BELLATRIX_FORK_VERSION: 0xAABBCC03
CAPELLA_FORK_VERSION: 0xAABBCC04
DENEB_FORK_VERSION: 0xAABBCC05
ELECTRA_FORK_VERSION: 0xAABBCC06
FULU_FORK_VERSION: 0xAABBCC07

# Activación inmediata de forks
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 0
FULU_FORK_EPOCH: 0